[package]
name = "my-redis"
version = "1.0.0"
authors = ["Wojciech Gawroński <afronski@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
